//Copyright (C) 2019 Arc676/Alessandro Vinciguerra <alesvinciguerra@gmail.com>

//This program is free software: you can redistribute it and/or modify
//it under the terms of the GNU General Public License as published by
//the Free Software Foundation (version 3).

//This program is distributed in the hope that it will be useful,
//but WITHOUT ANY WARRANTY; without even the implied warranty of
//MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
//GNU General Public License for more details.

//You should have received a copy of the GNU General Public License
//along with this program. If not, see <http://www.gnu.org/licenses/>.

// WikiSort sample program
// Generation of list permutations using Heap's Algorithm
// Input: the length of the list, N
// Output: all possible permutations of the integers in the range [0, N) as generated by Heap's Algorithm

#include <stdio.h>
#include <stdlib.h>

#include "allsorts.h"

int printArray(void** array, int len, int size, void* arg) {
	for (int i = 0; i < len; i++) {
		printf("%d ", ((int*)array)[i]);
	}
	printf("\n");
	return 0;
}

int main(int argc, char* argv[]) {
	if (argc != 2) {
		return 1;
	}
	int len = atoi(argv[1]);
	int* arr = (int*)malloc(len * sizeof(int));
	for (int i = 0; i < len; i++) {
		arr[i] = i;
	}
	heapsAlgorithm(len, (void**)arr, len, sizeof(int), printArray, 0);
	free(arr);
	return 0;
}
